import Footer from "@/layouts/Footer"
import Header from "@/layouts/Header"
import "../styles/globals.css"
import "../styles/footer.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
